namespace AdventOfCode2024
{
    internal class Day4_1
    {
        const string large_input = "SSSMXMMSMMXXXSMXMASXSAXXMSXSMSXMMSSMMMSMAMXMASASXSXMMSXXXMAXSMSXMAMSAMXMSMAMSAMAMMXSAMXMMSAMMMMSMMMSMMXMMSSMMXSMAMMAAMAMXSSXXXAMXXXSASMSSSSS\r\nMAASXMASAMXMXMMMXMMMSSMAXSAMXSAXMASAAAXMAAMMAAASMSAMSMAMSMMMXXXAMMMXMXMXAMAMAXMAXXAMXMAMXMAMAASXMAAAMXAMXAAXSAASASXMSMSXMXMASXSASMMMAMAAAAAA\r\nMSMMMMMSMMAAAAAMASAMMAXXXMAMASXMMXSXMMSSSSXMXMMMASAMXMAMAAASXSXMMSXAAAMSMSAXMMMSSMASASMSSSSMSXSASMSSXXASMXSMMMXMXMAAMXMASAMXMAXASXAMAMMMMMMM\r\nAAAXAAASXSXSMSASASAXXAMXMSAMXSSMSMMXSXAAAMXMAMASXSAMXSASMSMSAMXMAXSXMAXAAXAMXAMAAXMMMSAAAAXAMASAMXAAASAMMXXAMXAMSXMMMASMMASXMMMAMXXMXSXXXAMX\r\nSXSSMSXSAMAMXXXMMSASAMXAXAASAMXSAMXAXAMSMMASASASXMAMASASAMXMXMAMMXAMXSSMXMSASMMSSMXMXXMMMMMAMMMMMMMSMAAXSASAMMSXSAAMSAMASAMAAXMSMSSMSMMMSMMX\r\nAAXMAMXMXMAMMSAXAMASMASMSSSMASXAXMXXSXXAASXMASAMMMSMASASMMSSSSXSXSASAMAASAMMSAAAAMAMXXXXMAMXSMXSAMXXXMAXMASMMAXASAMMMXSXMASMMMSAMAAMSAAMASXM\r\nMAMSASAMAMXSAMXMXSAMXMAXXMAXXMAXSMXAMMXSXMXMMMMMAMAAMMXMAAAXAMXAASAMXMMMAAMXMMMMSSXSXXSSSXSASXAMAMASAXMSMXMAMAMAMAMXMASASAMXAMXASXXMMSMSASXA\r\nAXMMMMAMXAAMASAMXMASXSMSSSMSMSMAAAXXMAAXAMASAAASXMXXMAMSMMSSSMSSXMXMSXMSMSSSXXXAXMXMMXSAAAMAMMMMXMMSMMMAMXSAMSMMMAMAMASXMXASXSMMMAMMXMXMAMMM\r\nSXMAMSSMMMXSMMXMAMXMXASAAXAAMAMXAMXMMSXSASAXASMSXMSXMXAAXMAAAMAMXMXAXAXXXXAMAMAMMMMSASMMMXMAMAXSMSASAXMAXXMXSMAMSMSAMXSXMXMMMSMSAMSMAMXSMMXS\r\nXASAMAMXXMAMXMSSXSASXMMMMMXMSXMXMMXSAAMSAMMSAAMXAAMAMXSMSSMSMMSSSMASMXMMAMMMXMASAMMMXSAXXXXXXMSAAMASASMSMXXMAXAMAMAMXAMAMXAAAMASMMAXASXXAMAA\r\nSXSASMMMSSMMSMMAASAMAXSASAXMXXMAAAAMAMXMXMXAMMSSMMSMMAXMAXXXAAXAAXAXMAMAAXAAASXSXSAMXSXMXSXSMXMMSMXMAMAAXSXSXSXSXSMAMMSASMSMSMAMASXSXSAMMMMS\r\nSASXMXAAMAXMAAMMMMXSXMSAMASMAASMMMSSSMXSAMXMSAXXMMAAAXSXSXMXMMMSMMMXSAMSMSSSXSXSASMSMSXMXSAAMSXXAMMMSMMMMXAXAMAMAMXXXMSAXAAAXMASXMXXAXMASAXA\r\nMAMXMMMMSAMSSSMMXSAMXXMAMSMMMMXSAAAAAMAMAMXXMMXSASMSMSSMMASXAAAAAAAAXXMAXXXMASXMAMAMAMMMAMSMMSMSMSASAMMAMMMMMMAMAMSSMMMXMSMSMMMSAMXMMMXXSASA\r\nMAMAMXMAMAMXAAXMAMASAXMAMXAXSXASMMMMMMASAMXAAXAXMAXAXAMAMAMSSMSSSMSSMMSMXMMMAMXSMMXMAAAXXXAMXXAAASXMAMSASAAAXSXSMSAXAAAMXXMAXXASAMAMSASMMMMM\r\nSASAMASASAMMMMMMASXMMSSMXSAMXMMXSAXXXSASASAMXMMSXMMMMMSSMAMAMXAMAMAMXXASAAXMASMSAXXSMSSSMXSMMMSMMMMSSMSASXSSMMASXMMSSMSMSAMMMMMMAMAXAAXXAXAX\r\nSXSMSMSXSXMSASXSAXAAAMAAXMSMXASASXSMAMAMAMXMASAAMXASAMAXSAMAMAMSXMASXSASMSXSXMAXMMMAAXAAXAMAMAMMXMXAMXMAMMMMAXAMAAXMAMAASAMAXAAXMMMSMMMSXSXS\r\nSXMAAAMAMXXXAXAMASXMXMAMXXAXXSMASAAMXMAMXMMSAMSSXSXXASMMSMSMSSXMMSASXMXMXXAXAMAMSMSASMMMMXMAMXSMAMMMSAMAMXASXMAMAMXXMMSMSMMMSMSAAAAAMXAMAXAM\r\nMAMSMSMMSSSMSMAMMMAAAMSXSSMSXXMAMMMXXMASXAAMMMAXMXXSMMXAMXMAMMASAMMSMSASAMMMMMXSAAXMMAAMXSXSSMXMAMMXSXSXXMMAXXSMSMSSMAMAXXAXAAXMSMSMSMMSSMAM\r\nMAMXAXXXAAAAAMMMSSMMMMMAMXXSXMMSSXSAMXAMMMMSSSMMMAASASMXSAMAMXAMMMMXAXAMXSXAAMXMMSMMSSMMASXAXXAXMSMAMXMXAXSXSXMAAAAAMAMMMXMSSMMXMAMASAXAXAAA\r\nSASMMMSMMSMMMSSXMAXSAAMAMMAMAXXMAXAXMMASMSSXAXXAMAMSAMXAXASMSMMSXAXMSMXMXMMXMXAMXAXXAAXMASMAMSMMSAMASAAXMMSAMASXMMMMMXSXSXMAAXXXMAMXMXMASMXS\r\nSXXAXAXAXXASXAAASMMSMSSSMMASXMMSSMSXSAXMASAMXMMMSXXMAMMMXMMAAXAMMXXAXAAMXMASXMASMMMSSSMMASAAAXAXXAMSSMSXXAMAMMMAXXMASMMASAMSSMMMMSSMAXMXSAMX\r\nSXSMMXSSMSAMMMSMMAMXMMAMAMASXAMMMAAAXXXXXMXSXMMAXMASAMXAAMMMMMXSASMMMMXSXAMAMSAMASAMXXAMMMXSXSMASXMAXAXMMMXAMAXSMMSASAXASMMAAAAXAAMXMASAMASM\r\nXXAAMXMMAMXMAMAASMMSXMXSXMASMSMAMMMSMMMXMMAMMXAMSXASAMMSXSAMXMXMASXSAXSAMXMAXMASAMASXSMMSMMMMAAAAAMMMMAXAMXSSXXMAMMMSXMXSXMSSMMMMMMAMAMAXAMX\r\nSMSAMASAMXASASMMMAAMXMAXAMXSXAMASAAXMAAAXMAMXMMSXMXSAMAAASXMAMSMMMXAXMAAMXMXMSAMXSAMXAMAMXAMSAMMMMMXASAMSMAMAMASAMAASAMXSAXAXAAMAASXSSSSMMSX\r\nSAMMSAXSAMXSXSXASMMMAMASXMXSXMXAMMSSSSMMSSMMSASMMSMSMMXSAXXXAXAAAXSMXASAMXMMMMXSMSXSSSMSSMMXMXXAAXXSXSMAAMMSASMXASMMMASASMMXSMMSMXSAAXAXMMMX\r\nMAMAMASAMXMXAXMASMXXASMAASXSASMMXAAMMMAAXMXAXMAXXMAMXAMXMAMSMSSXMXAXMMXXMAXAMXMMAMAMAAAMMXMAMMMXMXAMXMMSXSMMAMXSXMMMMAMASXMMAMAXAXMMMMAMMAMX\r\nSAMAMMSXAAMMXMMMMMMSMSMSXSASAMASMMMSASMSMSMMXSSSSMMMMMXAMXXAXXAASXMXSAMASMSSMSMMSMAMXMASMASXSASAAMSMSXAMXSAMXMXMASASMSMMMAMMMSXSMMMXAAAASASA\r\nSXSSSMMMSAMXASXAAAAAASXMASAMAMAMASAMXSAAAAASAMAAAAXMAMMSMMSMXMSMMAXAMASAMMAMXAAXXXXSXSAAXXSAXASMXMAAMMSSMMASMMMSMMAXSAAAXAMSMMAMMAXMAXMXSASM\r\nXXAMXAAAAAMSMSSSMSXMXMAMAMASXMXSAMASXMXMSMAMMSMSMMSMXSAXAMXSAMASMXMMSAMMSMAMMMMMMSXMAMSSXXMAMXXMASMSMAXAASAMAAAAXMXMXSSMSMSMAMMMSMSAXXSAMAMX\r\nSMSSSSSSMAMAAMAXAMXSAMAMXSXMAMAMMSMMMSAMXXSXXSAMXMAAAMASMMASXSASMAAAMAXSAMMSXMAMAAAMXMMMXAMXMSASAMXXMXSAMMMSSMSSSMAMMMXMAXAMSMSMXMMMASMASXMS\r\nXAXAAXMAXAXMMMAMXMASAXXXMXAMXMMSASAAASASAAXXSMMMSSMSMAAMAMASXMXMMXMAMXMMASAAASAMXSSMAMAAAXXAAXAMXSAMXXMASMAAMAAXAXXXASASMXMMMAMAMXMAMASMMMMX\r\nMSMMMMSMMMSSSMXSAMXMAAMSSSXSASXMAXSMMXXMASMMXAAAXAXAXMXSXSXMXXXAAXAMSMSMSMMMXSAXAXMAMSMMSMSASMAMAMXSSMMAMXMASMMSSMSMAMMMXXMAMSMSSMSXXMAXAAMX\r\nMAMXAAXXMSAAXAXSXSAMXSAAMAAXASMMMMMMXSSXXAAXASMSSMMAXXMMASAXXMMSMMMXAAAXAAXXAXAMSSXSXSAMXAMAXXSMASASASMXSXXXXAXXAAAMXMSMSASXSAAAAAAASXSMXMXM\r\nSAMXMMSAMMMXMMMMMSXSAMMXMMMMSMXAMAXSAXMASXSXMMAXXXMSXXASAMAMXXAAAAAMMSMXSXMMMXAMXAXMMSAMMSMAMMXSASMSAMXMAXMMSMMSMSMSAAAAXMASMMSMMMXSAAMASXSM\r\nMASXAMMAXXXXAAAMAMAMXMAMXAAXMASMSSXMXSXXMXMAMXXMSXMAASMMXSAXXMSSSMSXXAAAMXMASXSXMMXMAXMMSAMXXXAMXSAMXMMXMASAAAXMAMASXMMXMXMAXXAXXXXXMAMASAAX\r\nSAMXMXSMMMXXXMXMASXMSMSMSSSSMXMAAMXSAMXSMXSAMXAMXAMMMMXAXSAMXXMAXAXMMMMMXAMASAXXXXAMMSSMSMSMMSMSAMXMSXMASMMXXSMXAMAMMXSSMAMMSSMSSXMXMMSAMXMM\r\nMXSXXAXAAAXMSSXMXSAASAMXAXMXMSMMMSMSAMASXAMASXAXSSMSXMMSMMMMMXMXMXAXXXAMAXMASMMMMSXSXAXASXSAAXMMXSSSMAXAAMASMXMMMSXSXAAXSASXAXMAMMAXXAMAMXSM\r\nASXMMSXSMSASAAASMMMMMAMMSSMAMMXXAAMXMMASMMSAMXMMMAAXMAAXAMASXSAXMMSMMSASMXMAXXAAXMAMMMMMMASMMXSXMAXAASMSSMAXXAMAMXAXMMMXMMSMXSMAXSXSMSSSMASX\r\nXMAMXMAXAMMMMSMMAAXAXXMXMMXAMXXMSMSSSMASAMMMMXMASAMMAMMSMSAXSAMXXAAAXAXAXAMXSSSSSXMSMMMXMAMAAASAMXSSMMAXXMASMMMSSMMMXXSMSMXMASMMXMAMAAAAMXMM\r\nSSMMAMSMMMAAXMMMMSSMSMSSSSSMSXMAMXAAXMXSMXSSSMMAXAMXXAAMAMXSXMAMMSSSMMMMSMSMAAXXMMMAAASAMXSXMXSAMMXMAMXMXMAXAAAAAAXAXXMXAAXMASAMAMAMAMSMSASX\r\nXAMMXMAAASXSSMASAAAXAAXAAMAAMMASXMMSMXMSAXAAAXMSMMMSMSAMXMSAXXSXAAXAAXAXAAAMXMXMMAXSXMMAXXSMSASXMMAXMMMSAMXSMMMSSMMSMASMMMXSMSMMMXAXXXAMXASX\r\nSMMASXXXMAAMXXAMMMMMMSMMMMMMMASXSMAAAXAMXMMSMMXAASAMAASXAMSMSMAMMSSSMSSSMXMXMXXMASXMASXSMAXAXXSXSMMMXAXMAMASMAXXMMAMXMSAAAXXAMASXSMSMMMSMMMX\r\nXAMASMSMMMXMAMMXSAMSXXAXXXMXMSAMAMMMXAMXXMXAXAMSXMASMMXSMAXXAMMAMAAAAXMXMASMSAXXXXASAMAXMSMSMASAMASMSSMSAMAMXXMAAMASMXSMMMSMAMXMAAAAAXAAAAXM\r\nSSMMMAAXMXAMXMXAMAXSASXSSMMAXMASMMMAMSSMXSXSXXAMXSAMXXXAMAMSMSXSMMSMSMSASASAMASMMMMMXMMMXXAMMAMAMAMAAAAXXMMMSMSXMXAMAMMMSAXXXMXMXMSSSMXMXMMX\r\nAAAMMSMSSSMSAMMMSAMMAMAXMASXXSMMXASMXAAMASMAMSSXMSAMMSMXAAMAXSAXXAAXXASASAMXMXMXAAXMAMXMMMSMMXSXMASMMMMXSAAASXSMSMMSSXMASAXXMMAAMXMAAAXSSSMS\r\nSSMMAXXAXAXSMSMMSXSMAMXMXMMMXAXMSASXMSSMASMAMXMAMSAMMAAASMSMMXXSMXSXMAMMMXMXXXXSXMMSAXAAAXAXMAMAMASXXMXMMAMXXASASXMAXAMASMSAASASMAMSMMMAAAXA\r\nMAMMXSMXSMMMXMMAMXSAMSXSXMAAMMSMAXMAXXXMASXMXSAMXSAMSMSMXXAXSSMXMAMXMSAMXMMMMMMSAMXSMSSSSSSSMXMAMMSXMXAXXXMSXAMMMAMASASAMAAMXMAMXAMAASAMSMMM\r\nMAMXAAAMSASXAXMMMAMSMMAMAMMSMAAXMAXMMAXMASAMASAMXMAXAAXMXSMSMMAAMASAXXAXXAAAAAASMMXSAAAAAAMAAAXAXXXMMSMXXAAXMMMXSMMMMMMAMAMXXMMMSMSSSMSXXAMX\r\nMSMMASXXSAMMMMMMMXSAMXAMAMXAMSSSMSSMSXXMASAMMSAMMXSSSXXMAMXMXASASAMAMMMMSSSSSMMSXMXMAMMMMMMMXMASMMAAXAAASMSMAAAXMASAAXSXMSXXSSSMAXAXMAMXMASA\r\nAAAXXMAXMSMAMASAMXAMSSSSXXSXMAAAXAAXSAMMASAMXSXMMSMAMSXMMXAMXXXAMXSAXAAAMXMXAXAXAXAXXMXMAMAXXXAXAMXSSMSMAAAXXXSMMAMXSMMASAMSMAASMMMSMAMAXAMA\r\nSSMMMAMXXAXXSASAXMMXAAXMAXMMMMSMMMSXXAMAXSMSAMAXXAMAMXSXSSMSAMMAMASXXXMMSAMMSMSXMMSMMMXSXSXXXMAXASXMXMAXMSMSASAXMASMMASMMSXAMSMMXAXAMMSSMMSS\r\nXAXAXSXMSMSXMASMMSXMMSMMMSMAAXAAXXMAMSMXXSMMASAMSXMASMMMAAAXAXSXMXMMMSAAMAMAXMXAAAXAAMASMAXSSMSSMMXMASMSMAXSMMAXSXMAXMMXAMSMXMXXXMSSSXAXAXAX\r\nXAMXMXAMXXAAMXMXAAAXMAMAAXXXSSMSXMAMXAAXAMASXMAMAASASAAXMSMMMMMXMAAAAXMXMSMMSASMMMSSMSASMAMXAAAXASMSAMXAXMXMXMAMXMMSMASMSMAMAMSMSMAMMMMSAMXS\r\nXSMSSSSMSXSSXSAMMSXMXAMASXXSAMMAASAMMMMAASAMXSXMMXMASXMSXAAASAMAMXMMSSSMAMAMMAMXAXXXAMAXMASMMMMSMMAMASXXMSAMXXXMAMAMMMMAXSMSMSMAAMAMAAXAXMXA\r\nAMAMAXMASAAXAMAMXMMMSMXAMAXMASXSMMAXSAMSXMAXXMMMMSMAMASXXMSMSASMXXASAAAMAMAMXMMSSMMSXMMMSMSXMAXXAMXMMSAMXSMSSSSSSSMSAXMSMXXXXMMSMSMSXXMMXMMA\r\nMMAMMMXAMMMMXMASMAAMAMMSMMMMAMAMASAMSAAAAMSMSMMSAMMSSMSASXMMSAMAAASMMSMMSMMMXXAXAAASAAXAXXSASMSSXMSMMMAXMXXAAXAAAAASAXMAMMMSSMAMXAAXXSSXMSAS\r\nXSXSXMMSXAXXXMAMMSMSMMMAAXSMSMXSAMAXSMMSSMXAAAAMASAAAXMAMMMAMSMMMMXAXMXMXASAMMSSSMMSSMMMXASAMAXXXXAXASMMSMMMSMMMMMMMAXMASAAAXMAMXMSAMXAAAAMM\r\nMAMXAXAXSSSSMMAMXMAMMASMSMAAAXXMMMXMXSAMAAMAMMMSMMMXXAMXMAMASXXXXXMSMXMMXAMASAAAXXMXMMASAXMAMXMMSSMSXMMAAAMAAAAXASAMXASASMSSSMASAMXAMSMMMMXS\r\nSAMSSMSXAXXAXSASAAMXSMSAMAMMMMMASAXMAMSSMMMMXMXSXMSSMSXMSSSMSXSMAXAAMXAAMSMMMMSAMXSSMMAXMMSXMXAAAAASXMMSXSMMMSMSASXSMMMASAAAXXASMSMMXSAMXXAX\r\nXAMAXAXMMMSSMSASXSXAMXMAXXXAMXSAMMMMAMMMXSAMMMAXAXAMXAAXAAAASAXSXMSASXSMMMAAXXXAMXSAMMSSXXXMSXMXMMXMASXAAXASAXAMXMXMAXMAMMMSAMXMXAAXAMMMMMMM\r\nSSMMASMMMAMXAMAMXXMAMAMSMXMXXXMASXAXXMXAASASAMSSMMSSMSSMMSMMMMMAXAMASMXAXMMMMASAMXSAMAMAXXSASXSSSMASMMMSXSAMMMAXXMMSAMMASXAXMSMMSASMMXAAMMSA\r\nMXAMAMAXMMMMSMAMXSAMXSXMAMSMMMSAMXMMSAMMMXAXMXMAXAMAXAXMAMMMAAXMASMXMAMMMXXAMMSAMXSMMAMMXMMAMXXAASXSXXXXAMXMMSSMMSAMXSMMSAMXAAXAMXXASXSXSAMM\r\nSSMMAMAMMSAAMSMSAXSXMXAMSMAAAAAASAMAXXXSAMSMMSMSMSXMMSMSAMMSSSSXSMSSMSAXMASAXAXAMXMASAASAMMAMXMSMMMXMASMAMAMAAMAMMMXMSAXSAMMSXSMMASMMAAAMMMX\r\nMXASXSSMAMMSMAMMMSMSASAMXSSSMSSMSAMXSXXMAXXASAAMMXAXXAASXSAMAMXXMAMXAMMSXXAMMXMAMXMMMMXXAXSSSSMAXAAAXAXAXMSMMMSAMMSAASMMSAXMAXAXMAXXMMMMMMXX\r\nSXMMMAMMXSAXMASAMAAAMXAMAXXAMXXMSXMMMMASMMSSMMSMASAMXAMSAMMSAMXSMSMSAXAMXMASAXSXMMXAAMSSSMAMAAXSSXSMSSSSMAXMMMSXSAMMXMMAXAMXMMMSMSMSXSXMAMAM\r\nXASMMMSAMMMMXASASMSMXXAMMSSXMASMSMSAAXAXAAXAXXXMXMAMSMXSAMXSASXXAAAMMMMMMMAMMMMAAMSSXSAAAMMMMMMXAMXAXMAAMXMASAMXMXSSSSMSSSMSXSXAAAXSASXSASAA\r\nXSMAASMMSAMAMMSAMAMAMSSMAAXMMMMAMASXSSSSMXSMMMMSASAMAMXSMMXXAMXMSMAMAAAXAMAMSASMSMMAMMMSMMXMAAXMASMMMMSMMASXMASXSAXMAXAXAAAAASAMXMXMAMASXSAS\r\nSXSMMSAASASMAXMAMAMAMAMXMXSMASMAMMMSXXXAMMAXAXAMASXXASMMASAMSMSMMXSSSSSSXSXSXXXMAXMAMSMAXMAXSXMMAMAXXMAXSXMXMAMMMXMMMMSMSMMMMMMXAXAMAMMMXMAM\r\nAAXMAXMMSXMXXXXAMXMXMMSAMMMMASXSMXMXMSXXMAASXSSMMMMSASXSAMAXMASAMMMAAAAAASMXMMMSAMXXSXSAXMMMXAAMSSMMMSMMMMSSMAMMMMSMMAAAXAMXAAXSMSMSMSXSXMAM\r\nMAMXMXSAMASAXSSSMMSMAMSXSAAMMSAMXAMAMASXXSMMAXAXAAXMMMMMXSMMMMMAMAMMMMMMAMMAXAAMAMMSMMMMSMSAMMMMXAXMAAMAAAAMXAMAAAAAMSSSMSMSSSXMXAMAXXAMSMAS\r\nMAMAMSMAXAMMMMAAXAAMXMMMXMMSAMAMSMXSAMAMMXAMXMXSMSMXSMSAMXAXMXSXMMSAMXAMAMXMMMXSAMXAAAXAAAMMXASXSAMMSMSMMMSXSSSSMSSSMMXXAAAXAMXXMSSSSMXMASAS\r\nSASASXSAMXMSAMAMMSXSASASMSAMXSMMXSAMMXMSSSMSSXMAXXASAAXAAMXMAMMAAAXASXXSXMASASXSXXXSSMSMMSMSSMSXMASXMASXMAMXAMAMAAAMMSXMSMMMMMXSAXAXMASXXMXS\r\nSAXMSXMXSAASMSMSXXAXXXASAMXXXMXSAMXMXAXAAAAMXSSSSSSSMMSXMSMSMSSMMMMXMMMMMSMSAMASXMXMMMSAAAAXAAMXSAMAMMMAMASMSMAMMMSMASAMXSAAAAAMXMMMSMASXMMM\r\nMSMXXAXAXMMMAAAMXMMMSMMMXMSMXSAMXAAMSMMMSMMMAXXAAXAMXXMXXXAAAMXAAMMMXAAXAAXMAMSMMSAAAAMAMSSXMMMAMSMXMASXMXSAASASAAXMMMXMAMXSMMXMMAXAAXAXMXAS\r\nAAMXMMMSSSXMSMSMMMAAAAAMAAMAXAXSSMMXAAXAAMMMSSMMMMMMMAXSMMSMSMSMMSAASXSSSSSMAMXAASXSMSSMMAAASAMXSXMASASASAMMMSXSMSXSAMXMSSXXMMSAMSMSSMMSASMS\r\nSMSAMXAAAAMMMXMXXMMMMSMSMMMAMMXXXASMSMMSMMMAMAXSXMXMSMXAAAAMXAXXASMMMMAXXAAXMAMMMSAMAXXMMXSMMAXSAXMAMXSXMASAMXXSAMAMMSAAAMMSAASAMXAMXMAAMAMX\r\nXXSASMMSSMMAXMASMSMXAMAXAXSAMXAMMMMAXMAAAAMASXMMXSAMAMMMMMSSMXMMMXMMSMSMMXAMXAAAAMAMSMAXMAXASMMMAMMASXMXSAMXMXMSAMSMASMMMMAMMMSAMMSMMXXSSSXS\r\nMASXMAMAMXSASXXAAAAMSMSMMMXAMXAXSAASMMSSSMSASAMXASXSASASAMXAXAMSMMSASXMASAMXSMSMXSXMASMMMMXMXAXMAMSASASASXSXSAASMMXMAXXAXXSXSXSAMXMASXAMAMMM\r\nMAMASXMAXAMXAMXMMMSMMAXAMAMXMSXMSAXMAXAMXXMXMXMMMSASASAMASMSMMMSAXMASASAMSAMXMAMXMASMXMXAMMXSAMSMXMXSXMAMAAASMMMAXSMXSMAMXMAMMSMMMXMMMMMAMXM\r\nMSSXMAMMMSSMMXAXAAXAMXSXMAXSAXAXXMMSMMSSMSXXMASXMXAMMMXSAMXAXSAMMMMAMMMAMAXMASASAAXXXMASAMAMMMMXMAMMMMMSMAMXMAASMMSMMAMASMMAMXXAAAASAMXSXMAS\r\nMAMMSSMXAAAAXMSMMXSAMXMAMAXMMSMMAAAXAAMAXXAASAMXXMXMAXMAXXMMSMAXSAMAMXSMXMASASXSMSMXSAMXSMSXSASXSAMAXAAMAMXXXSMSXXXSAAXMXAXXSSSSMSXXASXMXSMX\r\nMXSAAAAMMSSMMAMXXXAMSMSAMSMSAMXSSMXSMMSSMMSMMASXXXSSXSMMXMAMAXAMAMSAXXAAASAMASXSXAAMASAAXXMASASASXSSSMSSMSMSXAAXXMASXSMSMSMXMMXAAMMSXMAMASAS\r\nSAMMSSMXMAXAXSXAMXMMAMMXXXASXSXXAMMXAXXAXXMXSXMXSMAXSMXAASMMSXMSMASASAMSMXAMSMAXSXXXAXMSSMMMMXMAMAAASAMXAAASAMMMAMXMAMASAXXAMSXMMXMASMXMASMA\r\nMASAMXMXMASXMXMASAXSASMSSMXMAMXSAMSMMMXXXMMASAMXMAAMASMSMMAXAAMMXMMMMMXMXXSMMMXMAMMMMSAAMAMXSMMSMXMSMSMMXMSMAXAXXXAMMMAMMSAMXXXMXXMAMXXMMSXM\r\nSAMASXXMAXSXMMAXXMMSASAMXAAMAMMMXMXAAAMMMSMASASMMSXSAMXXASXMSSMSAXMMAXAXMAMAMASXXXAAAMMMMAMMXAMXMMXMAMXXMSAXSMMMSSMSSMASXMXMAXMMXMASXXSXMMMX\r\nMASAMMASMXSAAASMMMAMXMMMMSXSASXMSASMMSAAAXMASXAAAMAMAMSXMXSAAAXSAMXSSSMSXAMAMAMMMSMMSXXXSMSASXMAAMAMMMSMMSAMMAAAMAXAASASAMSMSMSAMXAMMMXXXAAX\r\nSMMMXSXMMASXMMMAMMAXAMMXAXASMSAXMASAAXXAMXSMSMMSXMASAMXAMAXMSSMMASXMAMMMMMMAMASAAAMAXXMXAMXXMMSSMSMSAAXSAMXMSXMMSMMSXMMSAMAAAAXXAMASXAAMSMSM\r\nMXAMMSSMMASAXAMAMMASXSAASXMMASXXMAMMMMXMXXSAMXXMASAXMXMAMXMAMXAMAMAXMASAASXMSASMSXMASASXXXXMMMAXMAXXMSSMSSSMSAMAAXAMXMASMSMSMSMAAMMMMMMXSAAA\r\nSMMSAXASAAXAMXSSMXMAMXMSMASMAMMMSMSAMXMMMMMMMMASMMMSAMSSMSAMXSSMASMMXMSMMSAAMASMMXMXSAMMMMMSAMXSMSSSSMAMMSXASAMSXMXSSMAXXAMXAMASXMSMSXSAMSMS\r\nAAMMMSMMMSSMSAMXAMXMASMAXXMMMXXAAXMASAAAASASAXMAMAAMAMAAASXMMAMMXMAMAMXMXSXMSAMAAAMMMXMAXAASMSMSAAAMMMAMXXMMMXMXASAMAMASMSSMXMAMXMMAXAMMMAMA\r\nSMMAAAAAAMAMXXXAXMAXXAXMXSXXSAMXSXMASXMMMSASXMXAMMSXSMSMMMAMXMSXSSMMAMMSAMAMMASMMXSAMXSSMMXXXAAMMMSMXXSXMMMSAMMXSMASAMXXAMMXMMAMSMMMMXMXSASX\r\nXAXMSMXMMSAMMMSMSSMSSMASAXXXMASXAXSASAMSAMMMMXSXMAMMAAAMASAMXXAAXAMSAMAAMSAMSXMASAXMAXAMXMASMMSMSAMXMMMASAASASMXXMXMASMMSMXAMMMXSAAMSMSAXMMM\r\nSXMMMMSAMSASAAAXAAAAASAMASXMSAMMAMMASAXMAMMAAMMAMAMXMSMSAMMXMMMSMMMSASMMXMAMXASAMMSMMXSMXSAMXAAXMASXMASMMSXSAMXMMXMAXMXAMASXSASXSXMSMAMMXSAM\r\nMMXXAXMAMSASMSSSSSMSXSMSMMXMAASXMMMAMXMSAMSMMSSSMMMXXAAMXSSSMAAAAAAMAMXXSSSMSXMASXAXSAMXAMMMSSXXAMXMMXXSAXMMMMMXSASAMXMSMAAASASMXXMAMMMAAMAS\r\nXXAMMMMAMXXXAAAMAXAXXMASXAXSXXMXAAMSSXAAAXAAAXXMASAMXMXMASAASMSSSMXMSMMAAAXASMSSMXASMMMMMSAXXXMSMMAXXASMMXMAAAXASAMXAXSAMXSMMXMXSMSSSMMMMSAM\r\nMMXMAMSMSXMMMMSMMMSMSMMMMSMSMSMSMMMASMSSSMMMMSASAMASAMSSSMSMMXAMMMXXAAMSMSMMMMXXAXMAAAAAMAMMMXAAAMXSSMMXAASMSMSAMAMASMSAMMAXAASMMAAAAMXAXMXM\r\nSMAMAXAAMAAMAAAAXAMAMXAAAXAMAAAMASMMXXAMMAXAMSAMASAAASAMXAAXSAMXAAMXMMMAMAXMXMAMXMAXSMSXSASAAXSXSAMXMAAMSXSAAAMXMXMMMASAMAMASXSAMMMSMMMMMXAM\r\nAAMSSSMSSXSSMSSSMSMAMSSSSMAMSMSMAMAXSMSSXSMMMMXMAMMSSMXSMSMXAMXSMSXSAAMASMXMAMASXSSXMAXXSAXMSMAAMMAASMMXMAMMMMMMSMSXMMMAMMXXMASMMXAXAMSSSSSS\r\nMXXAXSXXAAXXMAXMAAMXMMXMXMSMXAXMAXXMAAMXMXASXSAMASXXXAXXMXMSMMMXAAAMSMSXXXASXSMSAAXSSXSMMSMAAAMXXXSXSMSXSAAMASAAAAAXAXSXXXSAMXSXSMMMAMAAAAAS\r\nXMMSSMSMMMMASXSMSMSSXSMMAXXASXMMSASAMXMAXXAMASASASMSMSMXMAMAAMMMMMSMXMAXXMAXAAXMMMMXSASXAXMMMXAMMMMAMAMAAMMSASMSMMMAMMXMXMSXMASASASMSMMMMMMM\r\nMXAXMAXXMASXMASAAAXXAMMMXMMXMAMAAXSSSMSSSMAMXMAMAXAMAAXMXASMSMAAXAXMXSAMMMSMSMMXMASAMXMMMSMSXAXAAAMAMAMXMAAMMSAAAAXAMMAMAMXASMMMMMMAAXMASMXM\r\nAMSSMSMSSMSAMAMSMSMMXMASMMSMSMMASMMASAAAAMMMAMXMSMMMSMMSSMSAXMSMSMXSAMASXAAXAAMXMAMASXMXAAAAMAMXSMSMSAMXMMSSMMMXSMXXAXAMAMMXAXAAAXMSMMMAXAAX\r\nSAMXAAAAMXMXMXMXXXXMMMASAAAAASXAMAMAMSMSMMMSASMAMAAAXMAXAXMMMAXAAAAMASAMMSSSSSSMMXMXMXXASMSMMASAAASMSAMXAXXAXAMMMASXSSMSASMSMSXSSSMAMAMMSSSS\r\nMAAMMMSMSMSMMMMAMXMMAMASMMMXMSMSXMMXMAXAXMXMAXMASXMMSAMMAMMSMAMSMMMSXMAXXXAAAAAMMAMXMSXAMXMASASMMMSASAMSSMSMMSSXMAMAAAASAAAAXAXMXMMXMASXAAAM\r\nSSMMSXAXAAAASAMAAAASASAMAXSXXXAXXSAMXMSMSMAMSMMMSAAXMASMSAXAMXMAAMASXSAMMSMMMMMAMASAAMMMMMSAMASXSAMAMAMAAXXXMMXMMMMMMMMMAMXMSMMSAMSXSASMMMMA\r\nXAXSASMSMSMMSAXASMMAMMXSAASXMMSSMMASXXSAAXSXXMSAXMMMMAMAXSSMSSSSSMASAMASAAAAXXSMSAMMXMSMAAMMSMMAMASXSMMXSMSXXXSAASASXXAXMASXAAAAAMAAMAMAXMXM\r\nMMXSMMXAAXMASXMXXMXAXAXMMMMAMXAXAAAXAXMXMXXAMAMMSSMMMASASXMXMAMAMMMXXSAMMSSMSXXXAMSSMMAMMXMAAAMXMASXAXAXAMXSAASXXSAXMMASXMASMSMSMMXSMAMSXMSS\r\nSXAMXMSMMMSMMMMSAXXMMMXXAASMMMMSSMMSMMMSMSSXMAMXAAAAXAMXSAMXMMMAMMMMXMXMXXAMXMMMMXAAASMXSAMSXSMSMASMMMXMAMAAMAMAXMXMSSMSXMXMMMXAMXAXMXSXAAAM\r\nAAMSAMASAAAXMAMSAMXSAMSSSMMAAXMAXXMAXAXAAAAASXMMSXMMMMSMXAMXMASASAAXSASMMSAMXAASXMSSMMAAMMXMAAXXMAXAASMMSMSSMAMSMSAMMAAXXMASASMMSMXSXXMAMMAS\r\nMSMMMSASMSMXSSXXXMAMASAAMXXXMXMXSMSXSMSMMMMMMAXXXASXXAAAXSSXSASMSXSSMAMAASMMMSMXMAMAMMMMMSAMAMMXMAXSASAAXAMXXMAXASXXXMMMASASXMAMMMMXXAMXXXAX\r\nSAMXAMASXAAASXMASMSXMMMSMSMMSAMXSXSXSMAXSSXMSMSAXMMAMSXSXMAMMMSASMMXMMMMMMXSAAXMAMSAMSMMXMXXAXAXMAXMASMMMAMXSMMMXMMSSSXSXMXSMMMMAAAAAMSASMMS\r\nSXMMMMASXMSMSAMASXXAMAMAASAASASASAMASMMMAMAMAMXMXXAMXXXMXMAMSAMXMASMMAAAXAAMXSMMMXMMMAAAXMASMSSMMMSMAMAXSXMAXXMXSAXAAMMMAMASAASMSASXSASAMXSM\r\nMMSMSMASXMXXXAMAMASXMASMSSMMSAMXMAMAMAMAAMAMAXSXXMAXASMMXSAMSXSXXXMAXSMSMMSSMMMXMAAAXSSMXMASAAMXXMAXMMMMMAMMSASAAXMMSMAXAMASMMSAXXMAMAMXMMAX\r\nAMAAXMXMMXMASMMXSAXAXAMMAMXAMXMXMSMMSAMXMSSSMXSAASXMXSAAAXAMSAMMSMSSMMAMAMAXAAAAMMMMMXAMMMASMAMMXMSMSMSASXMAMMMMSXAXXXSSSMASAXMAMAMMMXMASXMX\r\nXSMSMSAAMSMAMAAXMASMMSSMAMAMSAMXAMAXMXSXAAAAMAMAMASXXXMMSMMMMAMAAXAMAMAMSXMXSMSSSSXSXXAMXMASXMMXSSMAAASAMMMMXXAMXMSXMAMAAMAXMMMAMAMXSXSASASX\r\nASAMASMMMAMASXMXAAAAAXAMSSSMMAXXMMAMAASMMMSMMASAMMMMSMSXXASMSMMSSSMMMSAMXASAMAMAAAASAMSMSSMMAXAMXAMMMMMXMASAMSXSXAXMASMSMMSSMMXXSASAMAMXSASM\r\nMMAMMMSSSMSASMMXMXSMMSSMMAAMSMMSMSMMMAMAXAAASXSMSXAAMXMASAMAAAMAMAXMASMMSAMXMAMMMMMMAMAAXMASMMSMSMMAXAXASMMXMXAMMSMSMMXXAAAMAXSASASAMXMXMAMA\r\nXSXMXAAXAAMAMMSASXXAAAAAMSMMAAXAASMMXASMMMXXMAMXXMMMSAMXMAMSSSMXMXMMAMAMAAMXSMSXXAXMXMMSMMMMMAAASXSMSMMMSXXXSMXMAMMSAMAXMMMMAMMAMASAMXSSMAMS\r\nXMAMMMMMMXMSMXMASXMMMMSMMAMSXSMMSMASXMSASMSSMAMMMSAASAMXSXMAMAMSSSXMASMAMXXAAXAMSMXMAXAXMMAAMMMSMAXXAAASMMSAAASXXSAMAMXMXASMSMMAMASAMXAAMMSM\r\nXXAMXAXSAMXAMMMSMXMAMXMAXAMMMMMXMMMMAAMAMAAXSMSMAMMXXAMXMAMASAMXAMSSXSXMXMMSSMMMAAASAMXSXMXSSMMXMMMSMSMSAASXMMMAAMASAMXSMASAAXSXMXSXMASXMSMM\r\nMMSXMASXASXMSAMAAXSAMSMSSSSSXMASMASXSMMMMMXMMSXMMXXSXSMAMAMMSMMMAMASAMXXAXMAXAAXMXMSAMXXAMSMXXXMASAMXXMMXMSAMXMMMMXMASAMMAMMMXMAMAMXXMASMAAA\r\nAXAAMSMMMMAAMAMMXMAAXAAMAXAXAAAMMXSAAMAAAMXMXAMMSMMXAMSMSXSMMASMXMASXSMSSSMSSXMSSMXSAMSMSMAASMSSXMAXAXXSMXSXMAMAAXXSXMXSMXSXSASAMMSMMXMAXMMM\r\nSMMSMAAXXSXMMSMMASMMSMSMXMASXMASXSMMMSSSXSAMSMXAAAXMXMAXAASASAXXMMASAMAAAAAMAAMAMSAMMMSAAMMSMAAMMXMMMSMMMXXSSXSSXSAMXMMSAMXASXXAXAAASAMMSSXX\r\nXAXXMSSMMMASAXASASXAAMXXXAXMASXXXAAAXAAXAMMXAAMSXSMAASMMMSMAMXSAMXAMAMMMSMMMSMMASMXXSAMXMSMAMXAAAASAMXAAMMMXXXAXASXSXMAMAXMMMMMMMSSXSASAAXXA\r\nMMMXMXXAAMXMASAMAXMXSMMSSMXXAMMSSSMMSMXMSMMSMSMMAMMSMSAASMMSMASAXAMSXMAMAMXXAAXSMMAAMMMAMAXXSMSMSMMAXXMMSASMMAMMAMXXAMSSSMXMASAMAMMMMMMMMSSX\r\nMAAAMMSMMMAMAMXMSMMAXAXAAAMMMSAAMXAXAMAMXMAAMAMXAXAAXXMMSAAXMXSXMXXXASMSSSMMSSMAAMSSSSSSSSSXSAMAMXSMMASASMSAMXXMAMXSAMXAMMASASAMMMASMSMXSAXS\r\nSASXSAMAASAMSXMAXAXASAMSSMAAAMMSSSMMASASAMSXSASMSMSMSMSMMMMSMMMXAXMSAMAAAXAXAMXSXMXAMAAAAASAMXMMXMASMMMASMSMMMXXXSAMSAMXMSASXXXMXSAMAAAMMSMA\r\nAAMMMASAMSASMAMSSMMMMMAMAMSSXSAAXAASXMAMXMAXMASXMAXAMAXXASAMXXAAXMXAAMMMSXXMASAXASMAMMMMMMMXMMMMMAAASXMAMASASAMSXMASAMXAMMMXAXSAMAXMSMMMAXXS\r\nMXMXSAMXXXMAMAMXAXSAAMSSSMAMXMMSMSMMSMXMSMMMSAMAMSMSMAMXAMXSAMXSMSMSSMXAMMSSMMASAXXXMASXXASMAMASMMSAMXMAXXSAMSAAXSXMMXSXMASMAMMAMAXXXAMMASMA\r\nSMMXMASXSSMASXSSMMXXMSAAAMSSSXXAAMXMAMAMXAAAMASXMXAXMAMXAXAMMAAXAAAXAMXXAAAAAXAMXMMSXMMSAMXAASMSAAXAMAMMXMMXMMSMMMMMMAMASASMMXSMMMMAMMMMAXAM\r\nAXXAXAXAMASASAMXMAXSSMMSMMMAMAMMXMAMMSSSSXMMSMMMAMXMSASMMMMSMSSSSMSMSXMMMMSSMMXSXAXMASAMMMMXMXMMMMSSMSASASXSAXXXMXAAMXSAMMSAXAXXAXMASASMSSSX\r\nMSXMXXSASAMXSAMXXAXMAMMAAAMAMMMSMSSMXMAAMMXAXAAAXMXAMMXXAAAAAXAAAAXMMAXXAAMAMSMMMSAMSMXXAAMMXSAXAAAAAXASASASXMXMMMSSSXMMXXXMMMSMXXSASXSAAAMA\r\nXMASAMSAMMXAMAMXMMXMAMSMSXSAXXAXMAMXMSMAMSMMSSSMSAMXMMMMSMMMSMMMMMMSXSAMXMMAMXAAAMMXXAMMSXSAASAMSXMMMMAMAMMMAMMSAAMAXAASXSMXAMAXSMMMSAMMMSMS\r\nMXAMAXMAMSMMSSMMSASXMMAXMMMMMMMSMASAMMSAAMAMAAAXSMSMSAMXMMXXMASAAXXMAXMMMXMAMXMMSMSAMAMMAAMMMMAMXAXMMMXMAMASXMAXMSSMSSMMAAXXXMXXSAAAMMMXMAXA\r\nMMSSXMSAAXAMAAAXMASASMMSXAAAXAAAXXSASMXXMMAMMXMMMAAAMXMAASXMSSSXSSSMAMXAAAMAMXXMMAMMXMMMMMMAXSXMSMMMMMMSMSAXAMMSMAAMAMMMSMMMSAMXSXMMSMSAMXXM\r\nXAMAMASMSXXMXSMMMAMXAMAMMSMSXXMMSMSMMXMASMMXSAXAMXMSMXSASXMASXMAMAMMAMSSSMXAXSMSMAMXXSXAASXMXSSXAXAMXAXAAMASXSXAMSSMAMMAAAXMAXMMSXSMSAMXSAMX\r\nMMSMMAXXMAXSMXMAMXSAMXAMMXSXXSMXXAXAAMMASAMAMXSMSAAAAXSMMAMXMAXXMAMSXMMAAMMSMSAAXAMSXMAMMMAMMMMSMSSMSASMMMMAAXMMXXXMAMMSSSMMSMSXMASAMXMAXASM\r\nMAAAMXSAMMMSAMSMSAMAXSXSXXASAMMASMMMMSMASXMASXMAAMMMSMSASXMASMMXMAMMMMMMXMAXAMSMMSSMAMASMSSMAAAXMAMXAAAXASMMXMMSAMSSMSMAAMASMAXAMAMMMMMMXAMA\r\nMSSSMASAASXMAMMXMASAMMXXXAMMSMAASAAXSXMASASASAMAMXSXAAMAMSAMXAAXSMSAAXASMSAMXMASAXAMXAASMAASXMSSMASAMXMAMSAXASXAASAAXAXMASXMMXMMMMSAAXAAMSXS\r\nXXAXMASXMMMSAMXAXMAMSAMXASXSMMMSSMMMMSMASMMXSMMAXMASMSMXMXMSAMXXXASMSSMSXMASASMSXSAMXMMSMSMMXAXXXASXXMASMSXMASXSSMXSMMXXMAMXXXXXSSSMSSXXXMAX\r\n";
        const string simple_input = "MMMSXXMASM\r\nMSAMXMSMSA\r\nAMXSXMAAMM\r\nMSAMASMSMX\r\nXMASAMXAMM\r\nXXAMMXXAMA\r\nSMSMSASXSS\r\nSAXAMASAAA\r\nMAMMMXMMMM\r\nMXMXAXMASX";

        string input => large_input;

        private char[][] Grid { get; set; }

        public int Count { get; set; }

        public object GetAnswer()
        {
            Grid = input
                .Split(new char[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries)
                .Select(line => line.ToCharArray()).ToArray();

            for (int rowIndex = 0; rowIndex < Grid.Length; rowIndex++)
            {
                for (int colIndex = 0; colIndex < Grid[rowIndex].Length; colIndex++)
                {
                    if (IsCellEqualTo(rowIndex, colIndex, 'X'))
                    {
                        var possibleCoordsForM = CheckAroundCellFor(rowIndex, colIndex, 'M');

                        foreach (var coordsForM in possibleCoordsForM)
                        {
                            (int Row, int Col) coordsDirection = GetCoordsDirection(
                                rowIndex, colIndex,
                                coordsForM.Row, coordsForM.Col);

                            Coords? coordsForA = GetNextCoordsFromDirection(coordsForM, coordsDirection);

                            if (coordsForA.HasValue && IsCellEqualTo(coordsForA.Value.Row, coordsForA.Value.Col, 'A'))
                            {
                                Coords? coordsForS = GetNextCoordsFromDirection(coordsForA, coordsDirection);

                                if (coordsForS.HasValue && IsCellEqualTo(coordsForS.Value.Row, coordsForS.Value.Col, 'S'))
                                {
                                    Count++;
                                }
                            }

                        }
                    }
                }
            }
            return Count;
        }

        private Coords? GetNextCoordsFromDirection(Coords? coords, (int Row, int Col) coordsDirection)
        {
            if (!coords.HasValue)
            {
                return null;
            }

            var newRow = coords.Value.Row + coordsDirection.Row;
            var newCol = coords.Value.Col + coordsDirection.Col;

            if (!AreCoordsWithinGrid(newRow, newCol))
            {
                return null;
            }

            return new Coords(newRow, newCol);
        }

        private struct Coords(int row, int col)
        {
            public int Row { get; set; } = row;
            public int Col { get; set; } = col;
        }

        private static (int, int) GetCoordsDirection(int rowIndex1, int colIndex1, int rowIndex2, int colIndex2)
        {
            return (rowIndex2 - rowIndex1, colIndex2 - colIndex1);
        }

        private List<Coords> CheckAroundCellFor(int rowIndex, int colIndex, char character)
        {
            var coordsList = new List<Coords>();

            for (int i = -1; i < 2; i++)
            {
                for (int j = -1; j < 2; j++)
                {
                    if (i == 0 && j == 0)
                    {
                        continue;
                    }

                    int rowCheck = rowIndex + i;
                    int colCheck = colIndex + j;

                    if (AreCoordsWithinGrid(rowCheck, colCheck))
                    {
                        if (IsCellEqualTo(rowCheck, colCheck, character))
                        {
                            coordsList.Add(new Coords(rowCheck, colCheck));
                        }
                    }
                }
            }

            return coordsList;
        }

        private bool AreCoordsWithinGrid(int rowCheck, int colCheck)
        {
            return rowCheck >= 0 && rowCheck < Grid.Length && colCheck >= 0 && colCheck < Grid[rowCheck].Length;
        }

        private bool IsCellEqualTo(int row, int col, char character)
        {
            if (row >= 0 && row < Grid.Length && col >= 0 && col < Grid[row].Length)
            {
                return Grid[row][col] == character;
            }

            return false;
        }
    }
}
